### ISSUE TITLE
prepare execve args

### ISSUE THREAD

**Issue by sjtobin** [crispPacketTriangle/minishell#32]
when a new variable is created, we need to update a new char** structure that has the env variables

**Comment by crispPacketTriangle** [comment]
execve takes char **env as a third argument.  This is how the environment variables are passed to the executing command.  Therefore, when the hashmap is updated with a new variable, it then has to be iterated and a char** object created that is substituted for char **env when execve is called (however, the subject doesn't require the possibility of temporary variables)

**Comment by sjtobin** [comment]
duplicate of #21
